# Alembic configuration for dagster-webserver auth database.
# The sqlalchemy.url is overridden at runtime by init_engine() callers.

[alembic]
script_location = .
sqlalchemy.url = driver://user:pass@localhost/db
